language: cpp

os: Visual Studio 2015 RC
platform: x64
configuration: Release

before_install:

install:

before_build:
  - cmake --version
  - mkdir build
  - cd build
  - export GTEST_SHUFFLE=1
  - cmake -LAH ..

build_script:
  - make VERBOSE=1
  - ctest -V
