language: cpp

compiler:
  - gcc
  - clang

sudo: required

matrix:
  include:
    - compiler: gcc
      env: GENERATE_COVERAGE=ON

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - if [ "$GENERATE_COVERAGE" == "ON" ]; then sudo pip install cpp-coveralls; fi

install:
  # Install latest g++ compiler
  - if [ "$CXX" == "g++" ]; then sudo apt-get install g++-4.8 -y --force-yes; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # Install latest cmake
  - sudo apt-get remove cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  - tar -xzf cmake-3.2.1.tar.gz
  - cd cmake-3.2.1
  - ./bootstrap > /dev/null
  - make -j8 > /dev/null
  - sudo make install
  - cd ..
  - rm -rf cmake-3.2.1 cmake-3.2.1.tar.gz
  # Install protobuf
  - sudo apt-get install libprotobuf-dev -y --force-yes
  - sudo apt-get install protobuf-compiler -y --force-yes

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1
  - ctest -V

after_success:
  - if [ "$GENERATE_COVERAGE" == "ON" ]; then coveralls --gcov /usr/bin/gcov-4.8 -i 'src' -r ../ --verbose; fi
