version: '1.0.{build}'
configuration:
    - debug
    - release
os: Visual Studio 2015
before_build:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
build:
    project: C:\projects\prioritybuffer\build\prioritybuffer.sln
test_script:
    - cd C:\projects\prioritybuffer\build
    - ctest -C %Configuration%
